# .github/workflows/watch.yml
name: Canyon-Bike-Watch

on:
  schedule:            # every 15 min (UTC)
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  watch:
    runs-on: ubuntu-latest

    steps:
      # 1 ▸ Check out the repo
      - uses: actions/checkout@v4

      # 2 ▸ Install Node (v20 is LTS as of May-2025)
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm                 # speeds up npm ci

      # 3 ▸ Install your package-lock deps (playwright, nodemailer, …)
      - name: Install npm packages
        run: npm ci

      # 4 ▸ Install Playwright browsers AND required system libraries
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      # 5 ▸ Run the watcher script
      - name: Run watcher
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO:   ${{ secrets.EMAIL_TO }}
        run: node watch-canyon.js

      # 6 ▸ Commit state.json only when it changed
      - name: Save new state
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.email "bot@users.noreply.github.com"
          git config user.name  "Canyon Watch Bot"
          git diff --quiet || { git add state.json && git commit -m "state update" && git push; }
