name: Canyon-Bike-Watch
permissions:
  contents: write

on:
  schedule:
    - cron: "*/15 * * * *"   # every 2 min just for the test
  workflow_dispatch:
jobs:
  watch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install npm packages
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      - name: Run watcher
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO:   ${{ secrets.EMAIL_TO }}
        run: node watch-canyon.js
      - name: Save new state
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.email "bot@users.noreply.github.com"
          git config user.name  "Canyon Watch Bot"
          # commit/push only when state.json differs
          git diff --quiet || { \
            git add state.json && \
            git commit -m "state update" && \
            git push; \
          }
